//-----------------------------------------------------------------------------
// Basic smoke tests + edge cases + face order tests for chamfer/fillet.
//-----------------------------------------------------------------------------
#include "helpers.h"

TEST_CASE(chamfer_basic_no_crash) {
    SS.NewFile();
    // After SS.Init(), SS.NewFile() has been called. We call it again to
    // get a fresh sketch (the harness called SS.Init() which includes
    // NewFile()+AfterNewFile()+GW.Init()).
    // The harness already called SS.Init() for us; just build the geometry.
    hGroup extrudeH = CreateBoxExtrude();

    // Verify extrude group exists and has a mesh.
    Group *eg = SK.GetGroup(extrudeH);
    CHECK_TRUE(eg != nullptr);
    CHECK_TRUE(eg->runningShell.surface.n > 0 || eg->thisMesh.l.n > 0 ||
               eg->displayMesh.l.n > 0);
}

//-----------------------------------------------------------------------------
// Task 2: Verify that FACE_XPROD entities are generated by the extrude group.
//-----------------------------------------------------------------------------
TEST_CASE(extrude_has_faces) {
    hGroup extrudeH = CreateBoxExtrude();

    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    CHECK_TRUE(face1.v != 0);
    CHECK_TRUE(face2.v != 0);
}

//-----------------------------------------------------------------------------
// Task 3: Chamfer phase 1 tests (edge-based)
//-----------------------------------------------------------------------------

TEST_CASE(chamfer_basic_no_boolean_fail) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup chamferH = AddChamferGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
}

TEST_CASE(chamfer_basic_has_mesh) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup chamferH = AddChamferGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    g->GenerateDisplayItems();
    CHECK_TRUE(g->displayMesh.l.n > 0);
}

//-----------------------------------------------------------------------------
// Task 4: Fillet phase 1 tests (edge-based)
//-----------------------------------------------------------------------------

TEST_CASE(fillet_basic_no_boolean_fail) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup filletH = AddFilletGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
}

TEST_CASE(fillet_basic_has_mesh) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup filletH = AddFilletGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    g->GenerateDisplayItems();
    CHECK_TRUE(g->displayMesh.l.n > 0);
}

//-----------------------------------------------------------------------------
// Task 5: Chamfer deep tests — self-intersection and shell face count
//-----------------------------------------------------------------------------

TEST_CASE(chamfer_no_self_intersection) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup chamferH = AddChamferGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    if(g->booleanFailed) return;

    g->GenerateDisplayItems();
    SMesh *m = &g->displayMesh;
    SEdgeList el = {};
    bool inters, leaks;
    SKdNode::From(m)->MakeCertainEdgesInto(&el,
        EdgeKind::SELF_INTER, /*coplanarIsInter=*/false, &inters, &leaks);
    el.Clear();
    CHECK_FALSE(inters);
}

TEST_CASE(chamfer_shell_has_surfaces) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup chamferH = AddChamferGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    if(g->booleanFailed) return;

    // A chamfered box should have more surfaces than a plain box (6).
    CHECK_TRUE(g->runningShell.surface.n > 6);
}

//-----------------------------------------------------------------------------
// Task 6: Fillet deep tests — self-intersection and shell face count
//-----------------------------------------------------------------------------

TEST_CASE(fillet_no_self_intersection) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup filletH = AddFilletGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    if(g->booleanFailed) return;

    g->GenerateDisplayItems();
    SMesh *m = &g->displayMesh;
    SEdgeList el = {};
    bool inters, leaks;
    SKdNode::From(m)->MakeCertainEdgesInto(&el,
        EdgeKind::SELF_INTER, /*coplanarIsInter=*/false, &inters, &leaks);
    el.Clear();
    CHECK_FALSE(inters);
}

TEST_CASE(fillet_shell_has_surfaces) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup filletH = AddFilletGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    if(g->booleanFailed) return;

    // A filleted box should have more surfaces than a plain box (6).
    CHECK_TRUE(g->runningShell.surface.n > 6);
}

//-----------------------------------------------------------------------------
// Task 7: Edge case tests (edge-based)
//-----------------------------------------------------------------------------

TEST_CASE(chamfer_edge_case_small_dist) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    // Very small chamfer distance — should not crash.
    hGroup chamferH = AddChamferGroupByEdge(extrudeH, edge, 0.01);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    // Pass as long as no crash; boolean may or may not fail for small distances.
}

TEST_CASE(chamfer_edge_case_large_dist) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    // Large chamfer distance (nearly the full face size) — should not crash,
    // but booleanFailed may be true.
    hGroup chamferH = AddChamferGroupByEdge(extrudeH, edge, 9.9);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    // Either succeeds or fails gracefully (booleanFailed=true), not a crash.
    // Just verifying no segfault/assertion.
}

//-----------------------------------------------------------------------------
// Task 8: Chaining test — two chamfers sharing the same face (entityB).
//
// This is a direct regression test for the ASSEMBLE duplication bug.
// Now using edge-based mode: each chamfer selects the edge between
// the shared face and a partner face.
//
// For a 20x20x20 box extruded from a 4-line square, there are exactly 4
// FACE_XPROD entities (one per LINE_SEGMENT, one per side face).
//   face[0]=front, face[1]=right, face[2]=back(opposite!), face[3]=left.
// face[0] is adjacent to face[1] (front-right) and face[3] (front-left).
//-----------------------------------------------------------------------------
TEST_CASE(chamfer_chaining_no_boolean_fail) {
    hGroup extrudeH = CreateBoxExtrude();

    // Collect all 4 FACE_XPROD entities from the extrude group.
    // The box has 4 side faces (front, right, back, left) as FACE_XPROD,
    // and top/bottom as FACE_NORMAL_PT (different type, not collected here).
    hEntity faces[4] = {};
    int found = 0;
    for(auto &e : SK.entity) {
        if(e.group != extrudeH) continue;
        if(e.type != Entity::Type::FACE_XPROD) continue;
        if(found < 4) faces[found] = e.h;
        found++;
        if(found >= 4) break;
    }
    CHECK_TRUE(found >= 4);

    // face[0] (front) is adjacent to face[1] (right) and face[3] (left).
    // face[2] (back) is OPPOSITE to face[0] — skipped.
    hEntity sharedFace      = faces[0];  // shared face for both chamfers
    hEntity chamfer1Partner = faces[1];  // chamfer1: front-right edge
    hEntity chamfer2Partner = faces[3];  // chamfer2: front-left edge (different edge!)

    // Find the edge entities between the face pairs.
    hEntity edge1 = FindEdgeBetweenFaces(extrudeH, sharedFace, chamfer1Partner);
    CHECK_TRUE(edge1.v != 0);
    hEntity edge2 = FindEdgeBetweenFaces(extrudeH, sharedFace, chamfer2Partner);
    CHECK_TRUE(edge2.v != 0);

    // Step 1: First chamfer on front-right edge — opA = extrude.
    hGroup chamfer1H = AddChamferGroupByEdge(extrudeH, edge1, 2.0);
    Group *c1g = SK.GetGroup(chamfer1H);
    CHECK_TRUE(c1g != nullptr);
    // The first chamfer must succeed (same geometry as chamfer_basic_no_boolean_fail).
    CHECK_FALSE(c1g->booleanFailed);
    if(c1g->booleanFailed) return;

    // Step 2: Second chamfer on front-left edge — opA = chamfer1H.
    // This is the EXACT scenario that triggered the bug: second chamfer on
    // an edge adjacent to the same face as the first chamfer.
    hGroup chamfer2H = AddChamferGroupByEdge(chamfer1H, edge2, 2.0);
    Group *c2g = SK.GetGroup(chamfer2H);
    CHECK_TRUE(c2g != nullptr);
    // KEY REGRESSION CHECK: the second chamfer on a different edge of the
    // same face must NOT fail.
    CHECK_FALSE(c2g->booleanFailed);

    // The final running shell should have more surfaces than a plain box (6 surfaces).
    if(!c2g->booleanFailed) {
        CHECK_TRUE(c2g->runningShell.surface.n > 6);
    }
}

//-----------------------------------------------------------------------------
// Task 9: Edge-based chamfer test — order 1 (face1, face2 → edge)
// With edge-based selection, face ordering is irrelevant since we select
// a single edge. Both "forward" and "invariant" tests use the same edge.
//-----------------------------------------------------------------------------
TEST_CASE(chamfer_face_order_forward) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup chamferH1 = AddChamferGroupByEdge(extrudeH, edge, 2.0);
    Group *g1 = SK.GetGroup(chamferH1);
    CHECK_TRUE(g1 != nullptr);
    CHECK_FALSE(g1->booleanFailed);
    if(g1->booleanFailed) return;

    int surfCount1 = g1->runningShell.surface.n;
    CHECK_TRUE(surfCount1 > 6);

    // Verify no back-facing triangles: all triangle normals should point
    // away from the box center (10,10,10). A flipped chamfer/fillet face
    // produces red back-facing triangles in the UI.
    g1->GenerateDisplayItems();
    Vector boxCenter = Vector::From(10, 10, 10);
    bool anyBackFacing = false;
    for(int ti = 0; ti < g1->displayMesh.l.n; ti++) {
        STriangle *tr = &g1->displayMesh.l[ti];
        Vector normal = tr->EffectiveNormal();
        Vector centroid = tr->a.Plus(tr->b).Plus(tr->c).ScaledBy(1.0/3.0);
        if(normal.Dot(centroid.Minus(boxCenter)) < -LENGTH_EPS) {
            anyBackFacing = true;
            break;
        }
    }
    CHECK_FALSE(anyBackFacing);
}

//-----------------------------------------------------------------------------
// Task 9b: Edge-based chamfer test — order 2 (face2, face1 → same edge)
// With edge-based selection, face ordering is irrelevant. FindEdgeBetweenFaces
// with reversed face order should return the same edge entity.
//-----------------------------------------------------------------------------
TEST_CASE(chamfer_face_order_invariant) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    // Reversed order: face2 first, face1 second — should find same edge
    hEntity edge = FindEdgeBetweenFaces(extrudeH, face2, face1);
    CHECK_TRUE(edge.v != 0);
    hGroup chamferH = AddChamferGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    int surfCount = g->runningShell.surface.n;
    CHECK_TRUE(surfCount > 6);

    // Verify no back-facing triangles: all triangle normals should point
    // away from the box center (10,10,10). A flipped chamfer/fillet face
    // produces red back-facing triangles in the UI.
    g->GenerateDisplayItems();
    Vector boxCenter = Vector::From(10, 10, 10);
    bool anyBackFacing = false;
    for(int ti = 0; ti < g->displayMesh.l.n; ti++) {
        STriangle *tr = &g->displayMesh.l[ti];
        Vector normal = tr->EffectiveNormal();
        Vector centroid = tr->a.Plus(tr->b).Plus(tr->c).ScaledBy(1.0/3.0);
        if(normal.Dot(centroid.Minus(boxCenter)) < -LENGTH_EPS) {
            anyBackFacing = true;
            break;
        }
    }
    CHECK_FALSE(anyBackFacing);
}

//-----------------------------------------------------------------------------
// Task 10: Edge-based fillet test — order 1 (face1, face2 → edge)
//-----------------------------------------------------------------------------
TEST_CASE(fillet_face_order_forward) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    hEntity edge = FindEdgeBetweenFaces(extrudeH, face1, face2);
    CHECK_TRUE(edge.v != 0);
    hGroup filletH1 = AddFilletGroupByEdge(extrudeH, edge, 2.0);
    Group *g1 = SK.GetGroup(filletH1);
    CHECK_TRUE(g1 != nullptr);
    CHECK_FALSE(g1->booleanFailed);
    if(g1->booleanFailed) return;

    g1->GenerateDisplayItems();
    int surfCount1 = g1->runningShell.surface.n;
    CHECK_TRUE(surfCount1 > 6);

    // Verify no back-facing triangles: all triangle normals should point
    // away from the box center (10,10,10). A flipped chamfer/fillet face
    // produces red back-facing triangles in the UI.
    g1->GenerateDisplayItems();
    Vector boxCenter = Vector::From(10, 10, 10);
    bool anyBackFacing = false;
    for(int ti = 0; ti < g1->displayMesh.l.n; ti++) {
        STriangle *tr = &g1->displayMesh.l[ti];
        Vector normal = tr->EffectiveNormal();
        Vector centroid = tr->a.Plus(tr->b).Plus(tr->c).ScaledBy(1.0/3.0);
        if(normal.Dot(centroid.Minus(boxCenter)) < -LENGTH_EPS) {
            anyBackFacing = true;
            break;
        }
    }
    CHECK_FALSE(anyBackFacing);
}

//-----------------------------------------------------------------------------
// Task 10b: Edge-based fillet test — order 2 (face2, face1 → same edge)
// With edge-based selection, face ordering is irrelevant.
//-----------------------------------------------------------------------------
TEST_CASE(fillet_face_order_invariant) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);

    // Reversed order: face2 first, face1 second — should find same edge
    hEntity edge = FindEdgeBetweenFaces(extrudeH, face2, face1);
    CHECK_TRUE(edge.v != 0);
    hGroup filletH = AddFilletGroupByEdge(extrudeH, edge, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    g->GenerateDisplayItems();
    int surfCount = g->runningShell.surface.n;
    CHECK_TRUE(surfCount > 6);

    // Verify no back-facing triangles: all triangle normals should point
    // away from the box center (10,10,10). A flipped chamfer/fillet face
    // produces red back-facing triangles in the UI.
    g->GenerateDisplayItems();
    Vector boxCenter = Vector::From(10, 10, 10);
    bool anyBackFacing = false;
    for(int ti = 0; ti < g->displayMesh.l.n; ti++) {
        STriangle *tr = &g->displayMesh.l[ti];
        Vector normal = tr->EffectiveNormal();
        Vector centroid = tr->a.Plus(tr->b).Plus(tr->c).ScaledBy(1.0/3.0);
        if(normal.Dot(centroid.Minus(boxCenter)) < -LENGTH_EPS) {
            anyBackFacing = true;
            break;
        }
    }
    CHECK_FALSE(anyBackFacing);
}
