//-----------------------------------------------------------------------------
// Entity generation + visibility tests for chamfer/fillet.
//-----------------------------------------------------------------------------
#include "helpers.h"

//-----------------------------------------------------------------------------
// Task 14: Entity-level tests for chamfer/fillet setback points.
// These tests check SK.entity directly (not just the shell/curves).
//
// Tests (a) and (b) document CURRENT behavior (should PASS immediately).
// Tests (c), (d), (e) describe DESIRED behavior (should FAIL until fixed).
//
// SAFETY NOTE: Always check e.IsPoint() before calling e.PointGetNum()
// because PointGetNum() will crash on non-point entities (e.g. FACE_XPROD).
//-----------------------------------------------------------------------------

// (a) Verify the chamfer group generates a FACE entity (IsFace()==true).
//     This should PASS (already implemented in group.cpp).
TEST_CASE(chamfer_group_has_face_entity) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hGroup chamferH = AddChamferGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // Check that at least one entity in the chamfer group is a face.
    bool foundFace = false;
    for(auto &e : SK.entity) {
        if(e.group != chamferH) continue;
        if(e.IsFace()) { foundFace = true; break; }
    }
    CHECK_TRUE(foundFace);
}

// (b) Document current behavior: point entities exist in chamfer group.
//     This should PASS (point entities generated by Task 2).
//     Purpose: baseline documentation test.
TEST_CASE(chamfer_setback_points_are_in_shell_not_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hGroup chamferH = AddChamferGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // Point entities ARE generated for chamfer groups (Task 2 fix).
    bool foundPointEntity = false;
    for(auto &e : SK.entity) {
        if(e.group != chamferH) continue;
        if(e.IsPoint()) { foundPointEntity = true; break; }
    }
    CHECK_TRUE(foundPointEntity);
}

// (c) After chamfer with dist=2.0, the setback points A, B, D, C should
//     exist as point entities in SK.entity belonging to the chamfer group.
//     Setback points (after orientation swap): A=(20,2,80), B=(20,2,0),
//     D=(18,0,80), C=(18,0,0).
TEST_CASE(chamfer_should_have_setback_point_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hGroup chamferH = AddChamferGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // Expected setback points after dist=2.0 (after orientation normalization swap):
    //   surf1=right(X=20): d1=(0,1,0)  => A=(20,2,80), B=(20,2,0)
    //   surf2=front(Y=0):  d2=(-1,0,0) => D=(18,0,80), C=(18,0,0)
    Vector A = Vector::From(20, 2, 80);  // V1 setback on right face
    Vector B = Vector::From(20, 2,  0);  // V2 setback on right face
    Vector D = Vector::From(18, 0, 80);  // V1 setback on front face
    Vector C = Vector::From(18, 0,  0);  // V2 setback on front face

    bool foundA = false, foundB = false, foundD = false, foundC = false;
    for(auto &e : SK.entity) {
        if(e.group != chamferH) continue;
        if(!e.IsPoint()) continue;  // MUST check IsPoint() before PointGetNum()!
        Vector p = e.PointGetNum();
        if(p.Equals(A)) foundA = true;
        if(p.Equals(B)) foundB = true;
        if(p.Equals(D)) foundD = true;
        if(p.Equals(C)) foundC = true;
    }

    CHECK_TRUE(foundA);
    CHECK_TRUE(foundB);
    CHECK_TRUE(foundD);
    CHECK_TRUE(foundC);
}

// (d) After chamfer, there should exist non-face entities (e.g. point or edge)
//     belonging to the chamfer group.
TEST_CASE(chamfer_edges_should_exist_as_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hGroup chamferH = AddChamferGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // Check for any entity in the chamfer group that is NOT a face.
    // This could be a point, line segment, or curve entity.
    bool foundNonFace = false;
    for(auto &e : SK.entity) {
        if(e.group != chamferH) continue;
        if(!e.IsFace()) { foundNonFace = true; break; }
    }
    CHECK_TRUE(foundNonFace);
}

// (e) After fillet with radius=2.0, setback points should exist as point
//     entities in SK.entity belonging to the fillet group.
//     For a 90-degree edge with r=2.0, setback = r/tan(45deg) = 2.0, giving
//     the same setback positions as chamfer dist=2.0.
TEST_CASE(fillet_should_have_setback_point_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hGroup filletH = AddFilletGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // For 90-degree edge, setback = r/tan(45deg) = r = 2.0.
    // Same setback positions as chamfer with dist=2.0 (after swap):
    Vector A = Vector::From(20, 2, 80);  // V1 tangent on right face
    Vector B = Vector::From(20, 2,  0);  // V2 tangent on right face
    Vector D = Vector::From(18, 0, 80);  // V1 tangent on front face
    Vector C = Vector::From(18, 0,  0);  // V2 tangent on front face

    bool foundA = false, foundB = false, foundD = false, foundC = false;
    for(auto &e : SK.entity) {
        if(e.group != filletH) continue;
        if(!e.IsPoint()) continue;  // MUST check IsPoint() before PointGetNum()!
        Vector p = e.PointGetNum();
        if(p.Equals(A)) foundA = true;
        if(p.Equals(B)) foundB = true;
        if(p.Equals(D)) foundD = true;
        if(p.Equals(C)) foundC = true;
    }

    // All four should exist (implemented in Task 3).
    CHECK_TRUE(foundA);
    CHECK_TRUE(foundB);
    CHECK_TRUE(foundD);
    CHECK_TRUE(foundC);
}

// (f) After chamfer with dist=2.0, LINE_SEGMENT entities should exist for the
//     4 boundary edges: surf1 contact (A-B), surf2 contact (D-C), top cap (A-D),
//     bottom cap (B-C). These are implemented in Task 4.
TEST_CASE(chamfer_has_line_segment_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hGroup chamferH = AddChamferGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // Count LINE_SEGMENT entities in the chamfer group.
    int lineCount = 0;
    for(auto &e : SK.entity) {
        if(e.group != chamferH) continue;
        if(e.type == Entity::Type::LINE_SEGMENT) lineCount++;
    }
    // Should have exactly 4 line segments for the 4 boundary edges.
    CHECK_TRUE(lineCount == 4);
}

// (g) After fillet with radius=2.0, LINE_SEGMENT entities should exist for the
//     2 contact edges: surf1 contact (A-B) and surf2 contact (D-C).
//     (Cap arcs at V1 and V2 are not generated here; they require ARC_OF_CIRCLE.)
TEST_CASE(fillet_has_contact_line_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hGroup filletH = AddFilletGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // Count LINE_SEGMENT entities in the fillet group.
    int lineCount = 0;
    for(auto &e : SK.entity) {
        if(e.group != filletH) continue;
        if(e.type == Entity::Type::LINE_SEGMENT) lineCount++;
    }
    // Should have exactly 2 line segments for the straight contact edges.
    CHECK_TRUE(lineCount == 2);
}

//-----------------------------------------------------------------------------
// Task 15: Original extrude vertices V1/V2 should be forceHidden after chamfer/fillet.
//
// When a chamfer/fillet removes the shared edge V1-V2, the point entities from
// the extrude group at V1 and V2 should have forceHidden=true so they don't
// appear as selectable green dots in the UI.

TEST_CASE(chamfer_original_vertices_hidden) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    // V1 and V2 BEFORE chamfer: extrude group point entities at (20,0,0) and (20,0,20)
    Vector V1 = Vector::From(20, 0,  0);
    Vector V2 = Vector::From(20, 0, 80);

    // Before chamfer: V1/V2 entities should NOT be forceHidden
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(!e.IsPoint()) continue;
        Vector p = e.PointGetNum();
        if(p.Equals(V1) || p.Equals(V2)) {
            CHECK_FALSE(e.forceHidden);
        }
    }

    hGroup chamferH = AddChamferGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // After chamfer: V1/V2 entities from the extrude group should be forceHidden
    bool foundV1 = false, foundV2 = false;
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(!e.IsPoint()) continue;
        Vector p = e.PointGetNum();
        if(p.Equals(V1)) {
            CHECK_TRUE(e.forceHidden);
            foundV1 = true;
        }
        if(p.Equals(V2)) {
            CHECK_TRUE(e.forceHidden);
            foundV2 = true;
        }
    }
    CHECK_TRUE(foundV1);
    CHECK_TRUE(foundV2);
}

TEST_CASE(fillet_original_vertices_hidden) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    Vector V1 = Vector::From(20, 0,  0);
    Vector V2 = Vector::From(20, 0, 80);

    hGroup filletH = AddFilletGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(filletH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // After fillet: V1/V2 entities from the extrude group should be forceHidden
    bool foundV1 = false, foundV2 = false;
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(!e.IsPoint()) continue;
        Vector p = e.PointGetNum();
        if(p.Equals(V1)) {
            CHECK_TRUE(e.forceHidden);
            foundV1 = true;
        }
        if(p.Equals(V2)) {
            CHECK_TRUE(e.forceHidden);
            foundV2 = true;
        }
    }
    CHECK_TRUE(foundV1);
    CHECK_TRUE(foundV2);
}

//-----------------------------------------------------------------------------
// Task 16: Original extrude LINE_SEGMENT V1-V2 should be forceHidden after chamfer/fillet.
//
// After a chamfer/fillet removes the shared edge V1-V2, the LINE_SEGMENT entity
// from the extrude group connecting V1=(20,0,0) to V2=(20,0,20) should have
// forceHidden=true so it doesn't appear as a visible edge in the UI.
//-----------------------------------------------------------------------------

TEST_CASE(chamfer_original_edge_hidden) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    Vector V1 = Vector::From(20, 0, 0);
    // Box height is 80: extrusion with valA=20 on the default workplane gives Z=80 at top.
    Vector V2 = Vector::From(20, 0, 80);

    hGroup chamferH = AddChamferGroup(extrudeH, face1, face2, 2.0);
    Group *g = SK.GetGroup(chamferH);
    CHECK_TRUE(g != nullptr);
    CHECK_FALSE(g->booleanFailed);
    if(g->booleanFailed) return;

    // After chamfer: the LINE_SEGMENT entity from the extrude group
    // connecting V1 and V2 should be forceHidden.
    bool foundEdge = false;
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(e.type != Entity::Type::LINE_SEGMENT) continue;
        // Look up endpoint positions
        Entity *ep0 = SK.entity.FindByIdNoOops(e.point[0]);
        Entity *ep1 = SK.entity.FindByIdNoOops(e.point[1]);
        if(!ep0 || !ep1) continue;
        Vector p0 = ep0->PointGetNum();
        Vector p1 = ep1->PointGetNum();
        if((p0.Equals(V1) && p1.Equals(V2)) || (p0.Equals(V2) && p1.Equals(V1))) {
            CHECK_TRUE(e.forceHidden);
            foundEdge = true;
        }
    }
    CHECK_TRUE(foundEdge);
}

//-----------------------------------------------------------------------------
// Chained chamfer test: chamfer1 on bottom edge, chamfer2 on top edge.
// After chamfer2, the EXTRUDE group's top-corner point entities (at V1=(0,0,80)
// and V2=(20,0,80)) and the LINE_SEGMENT entities touching them should be
// forceHidden=true.
//
// BUG: The current forceHidden loop checks `existEnt.group == opA`. For chamfer2,
// opA = chamfer1 group (NOT extrude), so extrude group entities are NOT found.
// This test SHOULD FAIL before the fix (Task 2) is applied.
//-----------------------------------------------------------------------------
TEST_CASE(chamfer_chained_second_hides_extrude_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    // Apply chamfer1 on (face1, bottom cap). opA = extrude group.
    hEntity bottomCap = FindCapFace(extrudeH, false);  // wantTop=false
    CHECK_TRUE(bottomCap.v != 0);
    if(bottomCap.v == 0) return;
    hGroup chamfer1H = AddChamferGroup(extrudeH, face1, bottomCap, 2.0);
    Group *g1 = SK.GetGroup(chamfer1H);
    CHECK_TRUE(g1 != nullptr);
    CHECK_FALSE(g1->booleanFailed);
    if(g1->booleanFailed) return;

    // Apply chamfer2 on (face1, top cap). opA = chamfer1 group.
    hEntity topCap = FindCapFace(extrudeH, true);   // wantTop=true
    CHECK_TRUE(topCap.v != 0);
    if(topCap.v == 0) return;
    hGroup chamfer2H = AddChamferGroup(chamfer1H, face1, topCap, 2.0);
    Group *g2 = SK.GetGroup(chamfer2H);
    CHECK_TRUE(g2 != nullptr);
    CHECK_FALSE(g2->booleanFailed);
    if(g2->booleanFailed) return;

    // The top-cap shared edge endpoints are at the corner between face1 (Y=0)
    // and top cap (Z=80). For the 20x20 box with front face Y=0:
    // V1 and V2 are the two endpoints of the top-front edge.
    // We check that ANY extrude-group point entity at Z=80 and Y=0 is forceHidden.
    bool foundAnyTopCornerHidden = false;
    bool anyTopCornerNotHidden = false;
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(!e.IsPoint()) continue;
        Vector p = e.PointGetNum();
        // Top-front corner: Z near 80 AND Y near 0
        if(fabs(p.z - 80.0) < LENGTH_EPS && fabs(p.y) < LENGTH_EPS) {
            if(e.forceHidden) {
                foundAnyTopCornerHidden = true;
            } else {
                anyTopCornerNotHidden = true;
            }
        }
    }
    // After chamfer2, ALL top-front corners from extrude group should be forceHidden.
    CHECK_TRUE(foundAnyTopCornerHidden);    // we found hidden ones
    CHECK_FALSE(anyTopCornerNotHidden);     // no unhidden top-front corners remain

    // Also check LINE_SEGMENT entities from extrude group touching those corners are hidden.
    bool anyTopEdgeNotHidden = false;
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(e.type != Entity::Type::LINE_SEGMENT) continue;
        Entity *ep0 = SK.entity.FindByIdNoOops(e.point[0]);
        Entity *ep1 = SK.entity.FindByIdNoOops(e.point[1]);
        if(!ep0 || !ep1) continue;
        Vector p0 = ep0->PointGetNum();
        Vector p1 = ep1->PointGetNum();
        bool p0IsTopFront = (fabs(p0.z - 80.0) < LENGTH_EPS && fabs(p0.y) < LENGTH_EPS);
        bool p1IsTopFront = (fabs(p1.z - 80.0) < LENGTH_EPS && fabs(p1.y) < LENGTH_EPS);
        if(p0IsTopFront || p1IsTopFront) {
            if(!e.forceHidden) anyTopEdgeNotHidden = true;
        }
    }
    CHECK_FALSE(anyTopEdgeNotHidden);  // all extrude edges touching top-front corner should be hidden
}

TEST_CASE(fillet_chained_second_hides_extrude_entities) {
    hGroup extrudeH = CreateBoxExtrude();
    hEntity face1 = {}, face2 = {};
    bool found = FindTwoAdjacentFaces(extrudeH, &face1, &face2);
    CHECK_TRUE(found);
    if(!found) return;

    hEntity bottomCap = FindCapFace(extrudeH, false);
    CHECK_TRUE(bottomCap.v != 0);
    if(bottomCap.v == 0) return;
    hGroup fillet1H = AddFilletGroup(extrudeH, face1, bottomCap, 2.0);
    Group *g1 = SK.GetGroup(fillet1H);
    CHECK_TRUE(g1 != nullptr);
    CHECK_FALSE(g1->booleanFailed);
    if(g1->booleanFailed) return;

    hEntity topCap = FindCapFace(extrudeH, true);
    CHECK_TRUE(topCap.v != 0);
    if(topCap.v == 0) return;
    hGroup fillet2H = AddFilletGroup(fillet1H, face1, topCap, 2.0);
    Group *g2 = SK.GetGroup(fillet2H);
    CHECK_TRUE(g2 != nullptr);
    CHECK_FALSE(g2->booleanFailed);
    if(g2->booleanFailed) return;

    bool foundAnyTopCornerHidden = false;
    bool anyTopCornerNotHidden = false;
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(!e.IsPoint()) continue;
        Vector p = e.PointGetNum();
        if(fabs(p.z - 80.0) < LENGTH_EPS && fabs(p.y) < LENGTH_EPS) {
            if(e.forceHidden) {
                foundAnyTopCornerHidden = true;
            } else {
                anyTopCornerNotHidden = true;
            }
        }
    }
    CHECK_TRUE(foundAnyTopCornerHidden);
    CHECK_FALSE(anyTopCornerNotHidden);

    bool anyTopEdgeNotHidden = false;
    for(int i = 0; i < SK.entity.n; i++) {
        Entity &e = SK.entity.Get(i);
        if(e.group != extrudeH) continue;
        if(e.type != Entity::Type::LINE_SEGMENT) continue;
        Entity *ep0 = SK.entity.FindByIdNoOops(e.point[0]);
        Entity *ep1 = SK.entity.FindByIdNoOops(e.point[1]);
        if(!ep0 || !ep1) continue;
        Vector p0 = ep0->PointGetNum();
        Vector p1 = ep1->PointGetNum();
        bool p0IsTopFront = (fabs(p0.z - 80.0) < LENGTH_EPS && fabs(p0.y) < LENGTH_EPS);
        bool p1IsTopFront = (fabs(p1.z - 80.0) < LENGTH_EPS && fabs(p1.y) < LENGTH_EPS);
        if(p0IsTopFront || p1IsTopFront) {
            if(!e.forceHidden) anyTopEdgeNotHidden = true;
        }
    }
    CHECK_FALSE(anyTopEdgeNotHidden);
}
